version: "3.4"

services:
  moviesapi:
    build:
      context: ./MoviesAPI
      dockerfile: Dockerfile
    container_name: moviesapi
    ports:
      - 8005:80
      - 8006:443
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      user: "sa"
      MSSQL_SA_PASSWORD: "Password_1234"
      ACCEPT_EULA: "Y"

  moviesapp:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: moviesapp
    ports:
      - "8000:80"
    depends_on:
      - moviesapi
