version: "3.4"

services:
  moviesapi:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8005:80
      - 8006:443
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@1234"
      ACCEPT_EULA: "Y"
    ports:
      - 14331:1433
